# -*- coding: utf-8 -*-
"""0311문제해결프로그래밍.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DwS-ZOAOJ-PoAP4ty0YJDy8mj7sa-SOr
"""

a= 100
b = 200
type(a+b)   # print 없이도 출력됨. 조금 있다가 다시 설명 나옵니다.

a = 11
b = 4
a / b

data = ['kim', 'lee', 'park']
for i in data:
  print(i)

def addValue(a, b) :
  result = a + b
  return result
hap = addValue (100, 200)
#print("100과 200의 합은 %d입니다." %hap)
print(f"100과 200의 합은 {hap}입니다.")

def func1() :
  a = 100
  print(a)
def func2() :
  global a
  a = 200

a = 0

func1()
print(a)
func2()
print(a)

a = [10, 50, 30, 40, 20]
print(a[0])
print(a[-1])
print(a[-4])
print(a[1:3])

def sumSquare(arr):
  result = 0
  for i in range(len(arr)):
    result += arr[i]**2
  return result
a = [1, 2, 3, 4]
print(sum(a))
print(sumSquare(a))

b = [1, 2, 1, 3, 2]
print(sum(b))
print(sumSquare(b))

d = {"정식":9500, "돈가스":9900}
d["쌀국수"] = 10000
print(d)
d["돈가스"]= 11000
print(d)

a = 100
b = 200
a,b